### ISSUE TITLE
OOM in Eden's Gate: Sepulture (Savage)

### ISSUE THREAD

**Issue by ahjsrhj** [xivdev/Penumbra#102]
When you enter Eden's Gate: Sepulture (Savage) when the plugin is enabled, the game will take up a lot of memory until it crashes

![image](https://user-images.githubusercontent.com/8666955/147685035-60089849-78eb-4b4d-9290-9e4822094868.png)

**Comment by Glasse** [comment]
Same thing happens to me every time even with everything else turned off.

**Comment by Ottermandias** [comment]
E4S is the only instance in the game that actively uses the new system we needed to circumvent in 6.0 (which is why the penumbra update took so long)
Our current workaround breaks when the system is actually used, which is why E4S just dies when using penumbra. We are aware, but not entirely sure yet on how to fix it correctly.
