### ISSUE TITLE
[Feature Request] Add priority next to mod name and sort by priority

### ISSUE THREAD

**Issue by Woedenaz** [xivdev/Penumbra#117]
It would be extremely useful if we could see the mod's priority listed before the mod name. For instance:
```
1. It's a Mod
2. 'Nother Mod
2. Yet another mod
2. Whoa another mod with same priority but after because I know my ABCs
21. Wow why does this mod have such a high priority?
```
so on and so forth.

It would also be quite useful if we could then sort said list by priority like the above. This would help a lot with knowing at a glance which mods are considered higher priority than others according to Penumbra.

As a bonus, adding the ability to edit said priority from the list view would be quite nice as well!

**Comment by Ottermandias** [comment]
You really should not have that many mods on separate priorities anyway.  The only mods where the priority matters at all are colored yellow (if they are solved) or red (otherwise), and you can filter for either of those. 
Also, sorting is and has to stay independent of collections, while priorities are collection settings.
