### ISSUE TITLE
sound getting weird wile using Penumbra

### ISSUE THREAD

**Issue by Rykia** [xivdev/Penumbra#123]
Hello, i have a problem...when i use Penumbra my sound in game gets weird....like you hear noises out of a radio....i tryd everything but nothing seams to work for me. When i remove Penumbra my sound is normal again. dose anyone has this issue too?

**Comment by BSoD38** [comment]
I seem to be getting this issue as well. I don't remember getting this issue before using pre-6.0. If I had to describe what it sounds like, it's like very short bursts of white noise. These short bursts happen multiple times in a second (between 2 and 5 times), and then it stops happening for a random period of time (about 5 - 20 seconds). It seems to happen more often on densely populated areas such as Limsa.

Here's a little disclaimer on my part though :
* I haven't personally pinpointed Penumbra as being the culprit in this issue, so it might be caused by FFXIV itself and not Penumbra
* All I remember is this issue not happening in FFXIV 5.58

I might try identifying this issue more precisely later.

**Comment by Ottermandias** [comment]
It's the XIV sound system that changed in 6.0 but I think the problem was linked to CPU utilization and thus might be increased due to plugins.
I don't think it has anything to do with Penumbra specifically, though.

**Comment by E-Tsx** [comment]
I also noticed this when using penumbra only(even when no mods are installed or enabled), the glitched sound comes from the ambient channel(if you mute this its fine). It seems to be the busy players near you samples that sorta plays in tiny bits, usually also continues to play for a few miliseconds when you exit game. The busy soundtrack also stops playing eventually if you just keep playing for hours.

**Comment by esibun** [comment]
I'm not sure CPU utilization is the issue - I was able to specifically pinpoint Penumbra as the issue after consistently relogging after toggling plugins.  I ran into this exact issue on a 5950X so I have plenty of CPU power on this machine.  I would assume that most of the processing that Dalamud/plugins does would be on a separate thread anyway.

Additionally, it's one specific sound that's playing: the crowd noise when you are in a populated area.  You can also go verify this by going to a populated area like Limsa Lominsa - the crowd sound was missing for me when I was having this issue.

I know this has been an issue for me for a while but I can't really say how long this issue has been happening since I only started running this plugin in 6.01.

**Comment by esibun** [comment]
Here's an attachment that shows the issue (volume raised to make the effect more obvious)

https://user-images.githubusercontent.com/2644839/151084819-9bd20d07-e9bc-409c-8a8f-912544eb41ed.mp4

.

**Comment by NotAdam** [comment]
@Ottermandias lol you reckon they've fucked something up with the streaming?

**Comment by NotAdam** [comment]
wouldn't surprise me at all if you could disable streaming and it fixes the crackling bs because of their dodgy changes to the sound engine

**Comment by E-Tsx** [comment]
Video above is exactly what I have too not the weird "chopper" effect that others seemed to have on AMD FX machines, it's hard to not point at the plugin, this is SE however so God knows what they have done with the EW patch regarding audio.

- Can't seem to reproduce it with only Dalamud loaded.
- If I enable penumbra as the only plugin and have 0 mods loaded(enable mods unchecked), restart game+PC and it's there. 
- Tested with both injection methods in XIV launcher, no changes.

I also noticed that I don't hear the crowd ambience crowd track at all anymore whenever I go to busy areas.

**Comment by Rykia** [comment]
e-tsx, its the same for me i have nothing else installed exept penumbra and the sound still is messed up, also i get the sound too when you log out, like you hear the sound from big fates our when many ppl are around, i dont know what to do our how to stop this but it drives me insane. so i hope we can figure out how to fix this since i rly like penumbra.

**Comment by Ottermandias** [comment]
Can you check https://github.com/xivdev/Penumbra/issues/130#issuecomment-1023483119 this out, too?
