### ISSUE TITLE
Feature request: Material pointer editing on models

### ISSUE THREAD

**Issue by Kylis** [xivdev/Penumbra#134]
I don't know how hard/easy/possible this is to implement but being Bibo+ user that likes using Gen 3 mods I constantly have to remake the mod pointing the models to the proper skin mesh. Would this be possible to implement in penumbra under editing as the only editing I end up having to do is point the model from the B skin material to the D skin material. It would save me so much time and effort to just be able to swap this in penumbra rather than having to load everything into textools, swap it, export mod, start over. If not thats ok, just figured I would check and put a request in if possible.

If need be I can make screenshots of where I edit the model settings.

**Comment by Zephyrai** [comment]
Adding to this as the oposite can be true aswell using gen 3 as base and wanting to use bibo mods. 
Currently textools got a Beta version out with a new feature called Auto Material Assignment so manual instalation of mods in textools with the feature enables will just sort themselves out to the coresponding skin material (provided you use a universal skin pack almost all mods are supported). Looking into this feature and if it is possible to provide the same via Penumbra could quite a nice QoL thing.

Here is the google doc Textools team has provided on the feature:
https://docs.google.com/document/d/e/2PACX-1vRQTFh4Mx6y-n8FXs0QgS4K_XtVqUDnwVwavYDp0JRyIXGl1dByP9LgPcGBshiVYoJC7TGBPoBaNRql/pub

Universal skin pack they released to introduce this feature:
https://www.xivmodarchive.com/modid/41351

**Comment by Ottermandias** [comment]
Penumbra does not read files itself - it uses game functions for that.
So the only option for penumbra would be to actively change those files, i.e. write them completely anew with some bytes changed. 
But that isn't really what Penumbra is about, so I don't think that's gonna happen.

But it seems like using this universal skin pack might just work with penumbra? You don't need to choose which material version to install in Penumbra but can just config that during runtime on the mod?

**Comment by Zephyrai** [comment]
The way i understood it the universal skin pack will have no problem in penumbra as it just populates skin files in the material slots A-F, wich will be nice in the futue when more universal packs are released to swap all skin textures at the same time (e.g change from textures close to tnf3 to bibo+ or a tatoo pack or something for all) without having to relog.

As for the mods that would otherwise "auto assign" with the use of textools will risk using the wrong skin materials unless the mod authors has spesifically assigned slots with the universal skin packs in mind or provide config options to swap wich material to use. However even without penumbra being able to support a simular feature, the process of converting the mods to use the right skin material will be simpler. Just having the feature enabled and then installing new mods via textools will correctly assign the skin material slot it is supposed to use. This skips having to assign skin material on every single item manualy before exporting the mod with the correct skin materials for the users setup. The exported mods can then be added in penumbra as usual.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/151672559-cc7dd9df-69a4-413c-abdc-6f5c86941c67.png)

**Comment by Zephyrai** [comment]
> ![image](https://user-images.githubusercontent.com/70807659/151672559-cc7dd9df-69a4-413c-abdc-6f5c86941c67.png)

Sweet! Seems to be working well from what i tested now, seems to convert both small and big mods without problem for now. Thank you so much for implementing this :)

**Comment by Kylis** [comment]
This works so well and so easily! Thank you, this saves hours of work overall!
