### ISSUE TITLE
.exd files are not correctly applied when importing from .ttmp2

### ISSUE THREAD

**Issue by QLEDHDTV** [xivdev/Penumbra#212]
Context - im using a fan-made russian translation that modifies many .exd files. After importing the mod and restarting the game, it does seem like some text is changed in the main menu (version and copyright), but after choosing a character it becomes quickly apparent that everything that is supposed to be translated still has original english text

**Comment by kosmicteal** [comment]
From what I can gather from the Debug tab, it looks like Penumbra doesn't recognize some vital exd files as them being used by the game (i.e. the one related to the main commands from the menu), and it doesn't even try to replace it for some reason. May be something related to Penumbra not reading some of the files loaded in the base package?

**Comment by endervad** [comment]
Hi, I'm the creator of the mod mentioned above. Our translation team would love to move from TexTools to Penumbra due to how much easier it is to manage files and import textures while also allowing users to avoid corrupting their game after updates. However this issue is a major roadblock for us since many crucial EXD files are not replaced and are indeed not even found in debug tab. Some examples of those files:
* Addon_0_en.exd (almost all of the in-game UI)
* Lobby_0_en.exd (main menu and character creation UI)
* Action_0_en.exd (action names)
* ENpcResident_0_en.exd (NPC names)
One thing I noticed though with Lobby_0_en.exd is that it's actually listed in debug tab, but despite file redirection being set up, Penumbra still draws the file from SqPack.

So I'd like to know if this issue is possible to resolve or it's something that goes out of limits of a Dalamud plugin? I can provide all the logs if needed.

**Comment by Ottermandias** [comment]
Do you have 'Wait for Plugins to load' enabled in the Dalamud settings?

**Comment by endervad** [comment]
I didn't, but now that I've tried to enable it, everything suddenly worked, thanks! Do you know just in case if there could be any issues with other plugins when this is enabled?

**Comment by Ottermandias** [comment]
As far as I know Penumbra and perchbirds ResLogger are the only plugins using the setting, so I don't think so, at least not any official or semi-official ones.
If this setting is not enabled, the game will generally load the earliest files before Penumbra becomes available, this includes EXDs and most Metadata files and such. With it enabled, Dalamud will stall the game launch until the plugins that actually subscribe to this loading mechanism (Penumbra and ResLogger) have finished constructing.

**Comment by endervad** [comment]
Alright, thank you very much! I think this issue can be closed then.
