### ISSUE TITLE
File path extension

### ISSUE THREAD

**Issue by Sevii77** [xivdev/Penumbra#216]
Files fail to load if the real path doesnt have an extension. `files/abc` doesn't work but if i rename it to `files/abc.tex` it does.

Mod with the problem attached.
[b4tHulMJsRZMazrc.zip](https://github.com/xivdev/Penumbra/files/8912723/b4tHulMJsRZMazrc.zip)

**Comment by Ottermandias** [comment]
Yes. Because files are identified by their extension by the game itself. Not a bug.

**Comment by Sevii77** [comment]
This used to work fine in the old version.

**Comment by Ottermandias** [comment]
Yes, but it should not, because the game identifies file types by extensions and not having the right extension is playing with fire.
It matters for .tex and .mdl because those have special treatment due to datamining protection.

**Comment by Sevii77** [comment]
I see, might be worth adding that penumbra simply ignores files without an extension for cases like this (Altho probably not worth, I know I'm probably the only one to try this.)

**Comment by Ottermandias** [comment]
You're actually not, Archon did a few days ago, too.
It's only relevant for .tex and .mdl - other files shouldn't be ignored? - because the part where I add their hashes to a set uses their extension. I could technically do this earlier when the file type enum is available but that would be kinda ugly. And I'm pretty sure it's much more conceptually secure to have the right extensions for every file.
Before 0.5 I just added the hashes of every file, even though we only need those of tex and mdl, so that was a bunch of unnecessary overhead.

If Penumbra actually does not find your files, and it isn't just not working with unnamed .tex/.mdl, that's probably due to it only  scanning for files at least one subfolder deep in the mod root.
