### ISSUE TITLE
Penumbra insists it isn't from the official repository when it is.

### ISSUE THREAD

**Issue by mikeshardmind** [xivdev/Penumbra#261]
This was pretty easy to fix on my end by just swapping the URLs and re-adding it, but the check used here seems slightly flawed.

![image](https://user-images.githubusercontent.com/22035876/206870745-56ee5b01-a92e-478b-bfb0-e5d3e0a4fa1f.png)

**Comment by Ottermandias** [comment]
If I had been aware of the other address to access raw files from github (or rather, thought of it - I technically knew about it), I'd have accepted both.
Now it's a "able to follow instructions" / "not using outdated guides" check, because all installation guides refer to the raw. address, so I'm not changing the check.
Anyone who uses this repo by choice and not by misguidance will also be able to fix their problem themselves anyway.

**Comment by mikeshardmind** [comment]
I'll note that had anyone added the repo from anything now considered an "outdated guide" (even those written prior to the link being included in this repository's readme) they lose access to settings. They, like me, may not have even noticed anything wrong for multiple weeks as it only blocks settings, not anything functional already configured.

But I'm the kind of person that would just fork to remove the check, including CI to automatically update the fork if it actually bothered me.

**Comment by Ottermandias** [comment]
Yes. They're supposed to use the stated repo. As long as they do not notice, it does not matter. If they change settings, they can change the repo. We have a lot of trouble with people installing from rehoster-repos that just increment API-level or whatever willy-nilly. This is meant to protect users not aware of the differences or results, of which there are a lot (sadly).

Of course you can feel free to fork, same as anyone providing their own version for whatever reason.

And this is surely a worthwhile way to spend ones time, instead of just changing your install!

**Comment by mikeshardmind** [comment]
As shown above, this *was* using this repo. This (my use) was configured prior to 11 months ago when the link was actually added to this repository's readme. You've framed this as a "users following directions" issue, but the change effects those who were using it prior to those instructions even being here.

**Comment by Ottermandias** [comment]
This is not 'the stated repo', it is a different address that coincidentally leads to the same file. I'm not talking about the github repo, but about the repo.json file, which is stated by address, which is supposed to be used.
Yes, this affects people with very old installs who never needed to update that. This is fine. They do need to update it now.

**Comment by mikeshardmind** [comment]
> We have a lot of trouble with people installing from rehoster-repos that just increment API-level or whatever willy-nilly. 

I imagine that those re-hosters are going to continue to do that, and just short-circuit this check.

> This is not 'the stated repo', it is a different address that coincidentally leads to the same file. I'm not talking about the github repo, but about the repo.json file, which is stated by address, which is supposed to be used.

It's literally the same file, from the same repo. In fact, GitHub did not used to redirect and used to just display it identically from each address. This url scheme is also documented

> Yes, this affects people with very old installs who never needed to update that. This is fine. They do need to update it now.

All that said, I've attempted to make the case in case other people less savvy about it end up being more impacted by it, but I don't personally care enough to continue doing so. I feel this change is short-sighted and misguided, but it's yours to make.

**Comment by Ottermandias** [comment]
> I imagine that those re-hosters are going to continue to do that, and just short-circuit this check.
No, they just publish a gigantic repo.json that includes crawled repos from github with their regular download addresses but custom API level. Anyone actually hosting a newly compiled version can of course also circumvent that.
