### ISSUE TITLE
Access to the path is denied.

### ISSUE THREAD

**Issue by Sjwoo13** [xivdev/Penumbra#318]
![image](https://github.com/xivdev/Penumbra/assets/22566760/161166de-45fd-4bfb-84ca-ea8af196328b)

Was working perfectly fine until today.

**Comment by Theo-Asterio** [comment]
Don't use that path as the error states and don't put penumbra and mare as the same directory. No idea what you're doing with .eij unless you provide more information. You shouldn't be using documents given onedrive messes up a ton of things on windows.

**Comment by Sjwoo13** [comment]
Penumbra and mare are not in the same folder. I just have it named that. idk what .eij is, it's for a mod. some mods work and some mods dont.

I don't think it's on onedrive. It's just on my SSD. nothing is in my onedrive.

**Comment by Theo-Asterio** [comment]
It's likely in Onedrive because windows by default syncs the documents folder. Onedrive is a cloud sync program not a specific drive on your computer. It causes issues with read/writing and is why it's not recommended to have your root directory in a folder like that. Change your root directory to somewhere more reasonable like C:/mods and try importing mods there, also ensure you don't have third party antivirus blocking things.

This would be much easier to solve on the discord and not github as you've provided no info on the mod.

**Comment by SerenitySublime** [comment]
Either way, it shouldn't be in your Documents folder. Move it out to the base of the drive at like c:\Penumbra instead of being nestled in folders like that.  But ya, its probably synced by OneDrive as it is in your Documents folder which is no bueno

**Comment by SerenitySublime** [comment]
Join the Discord. https://discord.gg/kVva7DHV4r

**Comment by Sjwoo13** [comment]
Ah. Okay. I will move to C: and ask any further questions on the discord. Thanks.

**Comment by Sjwoo13** [comment]
Changing to C: Fixed it.
