### ISSUE TITLE
[Suggestion] Sort installed mods alphabetically or by priority

### ISSUE THREAD

**Issue by Jonblu11** [xivdev/Penumbra#38]
While Penumbra 0.4's alphabetical support is great for finding mods, it's difficult to get a sense of the entire mod list's order at a glance. Being able to swap between 0.4's alphabetical and 0.3.5.2's priority sort would be very useful for organization purposes.

**Comment by Ottermandias** [comment]
Priority sort isn't really a thing anymore since priority is dependent on collection, not only on the mod list.
Priority should only be relevant for actually conflicting mods, and you can filter for mods with (solved or unsolved) conflicts in the list. You can also change the ordering for a mod in edit mode by changing the search name (and introduce folders).

**Comment by Jonblu11** [comment]
Yeah, that makes sense. Folders will probably solve my issue with organization, so I'll see what I can do with those.
