### ISSUE TITLE
Skin tone broken with no mods active

### ISSUE THREAD

**Issue by dagnys** [xivdev/Penumbra#418]
Logged in today and my skin tone was broken and has turned completely patchy black (see images, pale skin in second image is correct color). Clicking "disable mods" resolves the issue, but when I attempted to disable each of my mods manually to find which one was the problem, the problem persisted even after every mod had been disabled. My active mods have no unresolved conflicts. All my mods seem to be working, even body/skin ones, but they match current skin tone which is black. Hair is also changed - highlights are unaffected but base color is also black now. No idea what to do about this given that I have no way of determining which mod is the issue. 
![image](https://github.com/xivdev/Penumbra/assets/169950303/c42401d6-2c0e-4b45-93bc-48e4a50b5d46)
![image](https://github.com/xivdev/Penumbra/assets/169950303/49fe0545-2dc9-438a-b56f-ab3fe8f337e8)

**Comment by Theo-Asterio** [comment]
Can't tell much by the quality of the first screen shot but that just looks like a scale mod + dark skin, not weird patchy skin since I can see the scales vaguely in the second image. Second, the second image is presumably you using glamourer to change skin color which isn't going to show up on the login screen.  Third, you should probably go through all your mods because this wouldn't be a penumbra issue if it's a mod issue, it'd be you just not keeping track of your own mods.

If you have been using textools and not repairing that could also be your issue. We don't support the combined usage and start over isn't enough, repair with xivlauncher. Suggest you actually go to the discord for further support and explaining this more as the images don't show much without showing your mod list or mentioning if the difference between login screen vs game is because of your own glamourer customizations.

**Comment by dagnys** [comment]
> Can't tell much by the quality of the first screen shot but that just looks like a scale mod + dark skin, not weird patchy skin since I can see the scales vaguely in the second image. Second, the second image is presumably you using glamourer to change skin color which isn't going to show up on the login screen. Third, you should probably go through all your mods because this wouldn't be a penumbra issue if it's a mod issue, it'd be you just not keeping track of your own mods.
> 
> If you have been using textools and not repairing that could also be your issue. We don't support the combined usage and start over isn't enough, repair with xivlauncher. Suggest you actually go to the discord for further support and explaining this more as the images don't show much without showing your mod list or mentioning if the difference between login screen vs game is because of your own glamourer customizations.

The second image is an old screenshot from when my character model looked... correct. I was able to resolve it by reinstalling pretty much all my mods, but the settings are exactly the same as they were in the old collection; no idea what's going on there. Also, this dark skin is not a value that is possible to achieve in game, it is literally #00000.

**Comment by Theo-Asterio** [comment]
No, colors like that are possible via advanced customizations in glamourer. Where in the world are your mods stored, the exact path?

**Comment by dagnys** [comment]
C:\Users\SDM\OneDrive\Documents\FFXIV Mods for Au Ra Bods

**Comment by dagnys** [comment]
Also, correct on Glamourer - but I used Glamourer to try and fix the issue and it would not change my skin tone, even going through Advanced Customization. It registered my current tone as #00000 but would not change it when I input new values.

**Comment by dagnys** [comment]
Closing because I was able to resolve it myself; I doubt this is something wrong with Penumbra specifically because reinstalling mods fixed it but i am confused as to why it turned out this way.
