### ISSUE TITLE
Random crashes on loading screens

### ISSUE THREAD

**Issue by BSoD38** [xivdev/Penumbra#45]
Okay, so the problem is that I'm not 100% certain that Penumbra is causing this, but I seem to be getting this since I started using Character Collections on 0.4.x.x, so I guessed that it was caused by Penumbra.

Whenever I'm about to be in a loading screen, it could be when changing zones, loading duties, or even when starting an instanced battle (right after the cutscene), the game will sometimes simply close itself. I don't get any error dialog, and I don't see any errors in the Dalamud logs.

The problem is that this happens completely at random so testing this is complicated, but it will always happen on a loading screen. Sometimes I can play for several hours without issues, and sometimes it'll happen after 15 minutes of gameplay.

If you need more info I might be able to provide, please ask away.

**Comment by BSoD38** [comment]
I haven't been able to confirm that Penumbra causes these crashes, so I've been testing playing with my other plugins. I'll close the issue for now since the problem is unconfirmed.

**Comment by BSoD38** [comment]
Hello again.

I am reopening this issue as I have tested playing FFXIV for a full week with Penumbra disabled (and I haven't disabled any other Dalamud plugins besides this one), and I can confirm that Penumbra is the cause of the crashes.

So, as I said, crashes happen when a black screen is about to occur (teleporting, zoning, using aetherytes, loading a cutscene, etc). It happens completely at random, as sometimes I can play for a full day without crashing, and sometimes my game will crash 3 times in a single hour.

I have a character collection assigned to my own character, and have another mod group as a default collection.

Some of my mods have metadata manipulations, the ones that I remember using this the most is The HRBody 2.0 for Hrothgars 4K with SFW settings only, and Hrothgar & Viera Hats. I do have other mods that have meta manipulations for single outfits such as Summer's Flame Top for UHR2, Taffeta Shawl for UHR2, etc.

Mods that affect metadata are both in my character's collection and on default collection as there seems to be an issue with using metadata manipulation mods on character collections only (they do not work or don't load properly).

The game crashes when the screen is just about to fade to black. When it's about to crash, the game will freeze for a couple of seconds then immediately exit without any error message, and no error logs seem to be dumped in dalamud.log.

If there are other log files for Penumbra that I can look for, please tell me where to find them, and I'll be happy to do tests and supply logs to you.

Thanks!

**Comment by Ottermandias** [comment]
Thanks for your thorough information, but I am very aware, I just can't find the cause.
It is very probably not connected to collections or automatic redrawing, as people not using either do experience the crashes.
It seems to have a higher chance of happening the more mods you have. In particular, I rarely get the crashes and I never get them when I'm trying to get them to figure them out.
It may be connected to metadata manipulation files in some capacity, but I am not sure, it may also happen on regular files.
The crashes happen when unloading things - when following one crash in the debugger, it apparently crashed when reducing the RefCount of a loaded IMC resource (probably because the RefCount was 0 already when it should not have been or something), but I could not figure out why exactly.
The crashes do not occur before version 0.4.0, but reverting (as a user) would involve reverting a bunch of configuration, so I don't know if I'd recommend that.

I'll continue to try figuring it out, of course.

**Comment by BSoD38** [comment]
Thanks for the info, please do let me know if you need me to test something for you.

**Comment by Alkor1** [comment]
I tried disabling two mods not affecting gear to see if that was the issue. I'm not sure yet since I disabled them a couple days ago, but I didn't crash since then. 
One of them was on my eye texture. it was affecting the **limbal ring texture for female Aura** (mat A etc).
The other one was affecting, an housing item texture : **the Antecendent** painting.

**Comment by Ottermandias** [comment]
The crashes are very probably fixed on current builds of both API3 and API4.

**Comment by Alkor1** [comment]
I talked too soon, it just crashed again now.

**Comment by Ottermandias** [comment]
On what version?

**Comment by Alkor1** [comment]
Oops, I was sure I had the latest one, but penumbra.json says it's 4.2.6, sorry. I should have checked first.

**Comment by Ottermandias** [comment]
That's fine. Would've been devastating if the crash was on current :D

**Comment by BSoD38** [comment]
I have been testing the latest release for a few days, and had no crashes with the same mod list and mod settings. I'll consider this solved for now. Thanks!
