### ISSUE TITLE
[Feature Request] Be able to upload textures or models either in-game or by putting them in the file directory, in order to test mods faster.

### ISSUE THREAD

**Issue by lhWeiss** [xivdev/Penumbra#86]
Hi!

I am a mod creator. As good as the TexTools viewport is, it's not really the same as seeing the mod in-game. If possible, I would like in the future:

-  to be able to import texture and models directly into Penumbra so I can test my mods real-time, instead of having to quit the game and load them into TexTools everytime.

Thank you, and thank you for this tool <3

**Comment by DevJinnial** [comment]
Hmmm I am not sure this is something that could be done with Penumbra on it's on without another desktop tool HOWEVER. If you enable Lumina mode in TexTools, you can launch it while the game is running. When Lumina mode is enabled, any assets imported will be directly exported to a pre-defined folder in the same file structure that Penumbra can read and process instead of altering the game files. With that, you should be able to created a new mod in penumbra and just set that mod folder as your Lumina export directory in the TexTools settings. Here is an example image with it setup:

![image](https://user-images.githubusercontent.com/10831565/145751468-f1c448a1-bf52-4fa1-b5fd-7898cb0b0c71.png)

**Comment by lhWeiss** [comment]
That's exactly what I looking for! Thank you!
